apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres-n8n
  POSTGRES_PASSWORD: P4SSW0RD
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: postgres-n8n-no-root
  POSTGRES_NON_ROOT_PASSWORD: P4SSW0RD123